###Registrarse
POST http://localhost:8082/api/auth
Content-Type: application/json

{
  "fullName": "Willito vergara",
  "numberPhone": "3218982391",
  "email": "vergarw4illinton02135@gmail.com",
  "password": "12Wanda12",
  "birthday": "2000-08-22",
  "rol": "GUEST" ,
  "profilePhoto": "com.example.photo"
}

###Registrarse
POST http://localhost:8082/api/auth
Content-Type: application/json

{
  "rol": "GUEST" ,
"fullName": "Juan Bermudez",
"numberPhone": "3218982391",
"email": "carlos2133214@email.com",
"password": "121M21t2",
"birthday": "2000-08-22"

}

###Registrarse
POST http://localhost:8082/api/auth
Content-Type: application/json

{
  "rol": "GUEST" ,
  "fullName": "Elkin Bermudez Grajales",
  "numberPhone": "3218983231",
  "email": "elkinlol13@gmail.com",
  "password": "22eLkin12",
  "birthday": "2000-08-22"

}

### Iniciar sesion
POST http://localhost:8082/api/auth/login
Content-Type: application/json

{
  "email": "elkinlol13@gmail.com",
  "password":"11Elkin11"
}

###Iniciar sesion
POST http://localhost:8082/api/auth/login
Content-Type: application/json

{
  "email": "vergarwillinton04@gmail.com",
  "password": "12Wanda12"
}

### Enviar correo para recuperar contraseña
PUT http://localhost:8082/api/auth/change/password
Content-Type: application/json

{
  "email": "elkinlol13@gmail.com"
}

### Enviar correo para recuperar contraseña
PUT http://localhost:8082/api/auth/change/password
Content-Type: application/json

{
  "email": "vergarawillinton04@gmail.com"
}

###  recuperar contraseña
POST http://localhost:8082/api/auth/password
Content-Type: application/json

{
  "newPassword": "11Elkin11",
  "recuperationCode": "57547",
  "email": "elkinlol13@gmail.com"

}