###Crear cupon
POST http://localhost:8082/api/promotion/listings/f873a806-52da-44c2-b650-c44a3dbad7f1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2wiOiJIT1NUIiwic3ViIjoiMjExNjViMmUtZGEyMC00ZmQyLWE4YWYtOTUyNmQ1NTJkMWU5IiwiaWF0IjoxNzYwMjM4NjkzLCJleHAiOjE3NjAyNDIyOTN9.-_9EwBjq6FHt0Aflb0seWaYLsz2ZfNzXyGoOVwqo9R4pFxiHCDIvr3X79cne2DYD

{
  "createdAt": "2025-10-11T14:30:00",
  "expirationDate": "2025-12-31T23:59:00",
  "promotion": 15.0,
  "code": "COLOMBIA14"

}

