### Editar perfil desde GUEST
PUT http://localhost:8082/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2wiOiJHVUVTVCIsInN1YiI6IjQ0NDljYzNkLWIxY2QtNGY5MC05YTBkLTg3NjRkNDc2NWFhNyIsImlhdCI6MTc2MDExODIxNiwiZXhwIjoxNzYwMTIxODE2fQ.-5p8k3V6eWSI8t4bx4rMs-p17PZ-u3Jz1YXJJdmbyblZllX3-cDWnCImFKgXJXN8

{
  "fullName": "Willian ",
  "numberPhone": "3218982342",
  "profilePhoto": "https://www.pinterest.com/bobbie3jo/lol-dolls/"
}

### Eliminar cuenta
DELETE http://localhost:8082/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2wiOiJHVUVTVCIsInN1YiI6ImYzOGU0ZmM4LTRmZjktNGI3ZS04YTEzLTdjODZhYjcwODc5MyIsImlhdCI6MTc1OTgwNzUwNCwiZXhwIjoxNzU5ODExMTA0fQ.Ysj9j9_XhIJ9rQRumui6pGcbsOgrhyoJSwkfomGpKlLuTE1ZzP9749HevxLsmbq6

{
}

### Cambiar contraseña
PATCH http://localhost:8082/api/user/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2wiOiJHVUVTVCIsInN1YiI6IjQ0NDljYzNkLWIxY2QtNGY5MC05YTBkLTg3NjRkNDc2NWFhNyIsImlhdCI6MTc2MDExODIxNiwiZXhwIjoxNzYwMTIxODE2fQ.-5p8k3V6eWSI8t4bx4rMs-p17PZ-u3Jz1YXJJdmbyblZllX3-cDWnCImFKgXJXN8

{
  "oldPassword": "12Wanda12",
  "newPassword": "12wAnda12"
}

### Editar perfil desde HOST
PUT http://localhost:8082/api/user/host
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2wiOiJHVUVTVCIsInN1YiI6IjQ0NDljYzNkLWIxY2QtNGY5MC05YTBkLTg3NjRkNDc2NWFhNyIsImlhdCI6MTc2MDExODIxNiwiZXhwIjoxNzYwMTIxODE2fQ.-5p8k3V6eWSI8t4bx4rMs-p17PZ-u3Jz1YXJJdmbyblZllX3-cDWnCImFKgXJXN8

{
  "aboutMe": "Soy elkin el anfitrion pro",
  "documents": "Anexo1"
}

### Editar perfil desde HOST
PUT http://localhost:8082/api/user/host
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2wiOiJHVUVTVCIsInN1YiI6IjQ0NDljYzNkLWIxY2QtNGY5MC05YTBkLTg3NjRkNDc2NWFhNyIsImlhdCI6MTc2MDExODIxNiwiZXhwIjoxNzYwMTIxODE2fQ.-5p8k3V6eWSI8t4bx4rMs-p17PZ-u3Jz1YXJJdmbyblZllX3-cDWnCImFKgXJXN8

{
  "aboutMe": "Soy will el anfitrion pro",
  "documents": "Anexo1"
}


### Obtener perfil propio desde GUEST
GET http://localhost:8082/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2wiOiJHVUVTVCIsInN1YiI6ImMxMzEwMzY5LTk1N2MtNDAxMC1iMGM5LWFhMDRhMjU2OTViZiIsImlhdCI6MTc2MDE5MTkzOCwiZXhwIjoxNzYwMTk1NTM4fQ.ZV57AQlA9qTMpfXvpvxoJyxhBvQdlWIl3h3JbVYyQk3aEI13MDiCrbXtbBRlGilO

{

}

### Obtener perfil propio desde HOST
GET http://localhost:8082/api/user/host
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2wiOiJHVUVTVCIsInN1YiI6ImIwNGM2ZWJlLWNkMjctNGQyMC04YTFkLTMzNzg2NjVmMDAxMCIsImlhdCI6MTc2MDIwMzc5OSwiZXhwIjoxNzYwMjA3Mzk5fQ.MPYgCAU7tNNLzWMCBOsq0GbZ384CanrCccPiIRRrUtjpt1K8okAJs0obPPLnBR1q

{

}



### Pasar de GUEST a host
PATCH http://localhost:8082/api/user/host
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2wiOiJHVUVTVCIsInN1YiI6IjIxMTY1YjJlLWRhMjAtNGZkMi1hOGFmLTk1MjZkNTUyZDFlOSIsImlhdCI6MTc2MDIxNjAwOCwiZXhwIjoxNzYwMjE5NjA4fQ.aP63jXhRfD-k2QV2QIZhm94o6k_mch_1Wuw4tLDipXwMH1CccNOes-s2rKB7WQLF

{
}



###Pasar de Hot a guest
PATCH http://localhost:8082/api/user/guest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2wiOiJIT1NUIiwic3ViIjoiYjA0YzZlYmUtY2QyNy00ZDIwLThhMWQtMzM3ODY2NWYwMDEwIiwiaWF0IjoxNzYwMjA1NTU4LCJleHAiOjE3NjAyMDkxNTh9.jxrFu_6hVbSfE4xvVmpA8Nt0VIlilXU-QBnlXR3eJr2_G9A1ktga8rfnSpF_cS4f

{

}